#if !defined(AFX__REPORTTITLES_H__E81CD7A2_47FD_4AB2_BAD4_1F3142664287__INCLUDED_)
#define AFX__REPORTTITLES_H__E81CD7A2_47FD_4AB2_BAD4_1F3142664287__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class C_ReportTitle;

/////////////////////////////////////////////////////////////////////////////
// C_ReportTitles wrapper class

class C_ReportTitles : public COleDispatchDriver
{
public:
	C_ReportTitles() {}		// Calls COleDispatchDriver default constructor
	C_ReportTitles(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	C_ReportTitles(const C_ReportTitles& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void Add(LPDISPATCH ReportTitle);
	void Remove(short Index);
	void Clear();
	short Count();
	C_ReportTitle Item(short Index);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__REPORTTITLES_H__E81CD7A2_47FD_4AB2_BAD4_1F3142664287__INCLUDED_)
