//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TMeter.rc
//
#define ID_EDIT_STD                     3
#define ID_INSERT_STD                   4
#define ID_DELETE_STD                   5
#define ID_DELETE_ALL                   6
#define ID_OPEN_FILE                    7
#define ID_SAVE_FILE                    8
#define IDD_ABOUTBOX                    100
#define IDD_MDICALIBVIEW_FORM           102
#define IDR_MDICALIBVIEW_TMPL           103
#define IDR_MAINFRAME                   128
#define IDR_TMETERTYPE                  129
#define IDR_MDIFRAME_MENU               130
#define IDR_MDIFRAME_TYPE               130
#define IDD_MDIMEASUREVIEW_ZH           133
#define IDD_SPECTRUMDLG                 134
#define IDD_CONDITIONMONITORDLG         135
#define IDI_STOP                        138
#define IDI_START                       139
#define IDD_MDISPECTRUMVIEW_ZH          140
#define IDR_MDISPECTRUM_MENU            143
#define IDR_MDISPECTRUM_TYPE            143
#define IDD_SETZONE                     146
#define IDR_MDI_TOOLBAR                 149
#define IDI_MOVEL                       152
#define IDI_MOVER                       153
#define IDR_MDISTBTEST_MENU             154
#define IDD_STBTESTDLG                  155
#define IDD_PERIODICTABLEDLG            162
#define IDD_CREAWORKZONEDLG             163
#define IDD_PUREELEINTENSITYDLG         164
#define IDD_DEFMADLG                    166
#define IDD_TAB_DEFPRODUCT              167
#define IDD_TAB_DEFAPP                  168
#define IDD_TAB_DEFUNIT                 169
#define IDI_SWITCHWZ                    171
#define IDI_OPENWZ                      172
#define IDD_CONFLAYERDLG                173
#define IDD_WORKZONELISTDLG             174
#define IDD_TIMETICKDLG                 175
#define IDD_DEF_SAMPLE_DLG              176
#define IDD_DEF_CONDITION_DLG           177
#define IDD_DEFMALISTDLG                178
#define CG_IDD_PROGRESS                 179
#define IDD_STDSAMPLEDLG                182
#define IDD_CONFSAMPLEDLG               183
#define IDD_COLLDLG                     186
#define IDD_SET_MEASHEARD_DLG           187
#define IDD_SET_XYZ_DLG                 188
#define IDD_SET_CROSS_DLG               189
#define IDD_ENERGY_CALIB_DLG            190
#define IDD_ENERGY_CALIB_DLG2           191
#define IDR_MDICALIB_TYPE               193
#define IDC_BTN_START                   1000
#define IDC_BTN_STOP                    1001
#define IDC_SPECALZ                     1003
#define IDC_VIDEO                       1003
#define IDC_OPENWZ                      1004
#define IDC_SPECTRUM                    1005
#define IDC_SWITCHWZ                    1005
#define IDC_WZNAME                      1006
#define IDC_HV_STATIC                   1007
#define IDC_MA_STATIC                   1008
#define IDC_STD_STATIC                  1009
#define IDC_H2500_STATIC                1010
#define IDC_TEMP1_STATIC                1011
#define IDC_TEMP2_STATIC                1012
#define IDC_SETPARAM                    1013
#define IDC_SETTIME                     1014
#define IDC_SETHV                       1015
#define IDC_WZTITLE                     1015
#define IDC_SETMA                       1016
#define IDC_SPECTRUMEX                  1016
#define IDC_SET2500                     1017
#define IDC_COLOUR_LIST                 1017
#define IDC_UTEMP                       1018
#define IDC_BTN_MEASURE                 1018
#define IDC_LTEMP                       1019
#define IDC_BTN_STB                     1019
#define IDC_LASTRESULT                  1019
#define IDC_OPENTUBE                    1020
#define IDC_STATISTIC_LIST              1020
#define IDC_CLOSETUBE                   1021
#define IDC_ARRAY_LIST                  1021
#define IDC_CHANNEL                     1021
#define IDC_OPENSHUT                    1022
#define IDC_MOVERIGHT                   1022
#define IDC_CLOSESHUT                   1023
#define IDC_MOVELEFT                    1023
#define IDC_OPENLAMP                    1024
#define IDC_CLOSELAMP                   1025
#define IDC_BASE                        1025
#define IDC_SETTOPLINE                  1026
#define IDC_TOP                         1026
#define IDC_SETBASELINE                 1027
#define IDC_BASESPIN                    1027
#define IDC_TOPSPIN                     1028
#define IDC_STARTSTB                    1028
#define IDC_STOPSTB                     1029
#define IDC_STBPROGRESS                 1030
#define IDC_STBREPORT                   1033
#define IDC_TESTTIME                    1034
#define IDC_SAMPLETIME                  1035
#define IDC_CLEANLIST                   1036
#define IDC_SAVELIST                    1037
#define IDC_CHANNELS                    1037
#define IDC_LOADLIST                    1038
#define IDC_CHANNEL_SPIN                1038
#define IDC_CHS_STATIC                  1040
#define IDC_ALL_STATIC                  1041
#define IDC_PURE                        1042
#define IDC_ELENAME                     1043
#define IDC_LEFT                        1044
#define IDC_RIGHT                       1045
#define IDC_HV                          1046
#define IDC_START                       1047
#define IDC_STOP                        1048
#define IDC_SAVE                        1049
#define IDC_PROGRESS                    1050
#define IDC_SETCFG                      1051
#define IDC_SAVEPUREWIN                 1052
#define IDC_SAVEPUREDATA                1053
#define IDC_CLOSE                       1146
#define IDC_CLEANALL                    1146
#define IDC_WZTAB                       1149
#define IDC_SAVEALL                     1150
#define IDC_ACCEPT                      1151
#define IDC_TAG                         1151
#define IDC_ALLELEMLIST                 1152
#define IDC_CANCEL                      1153
#define IDC_THICKMODE                   1153
#define IDC_LAYERTREE                   1154
#define IDC_MODIFY                      1155
#define IDC_CAILB                       1156
#define IDC_NEW                         1157
#define IDC_CMPSA                       1159
#define IDC_CANCL                       1162
#define IDC_ISMQ                        1163
#define IDC_HV30KV                      1164
#define IDC_HV40KV                      1165
#define IDC_HV50KV                      1166
#define IDC_FILTER_NI                   1167
#define IDC_FILTER_NONE                 1168
#define IDC_FILTER_AL                   1169
#define IDC_COMMENT                     1170
#define IDC_BECMSCALE                   1171
#define IDC_BECMOFFSET                  1172
#define IDC_THICKMODE0                  1172
#define IDC_BEMEASURE                   1173
#define IDC_THICKMODE1                  1173
#define IDC_BEFILTER                    1174
#define IDC_THICKMODE2                  1174
#define IDC_CONTENTMODE0                1175
#define IDC_CONTENTMODE1                1176
#define IDC_CONTENTMODE2                1177
#define IDC_ELEMLIST                    1178
#define IDC_ADD                         1179
#define IDC_REPLACE                     1180
#define IDC_DELETE                      1181
#define IDC_RECONTENT                   1182
#define IDC_ELEMCOMBO                   1184
#define IDC_ELEMCONTENT                 1185
#define IDC_ELEMDENSITY                 1186
#define IDC_DENSITY                     1187
#define IDC_THICKNESS                   1188
#define IDC_SATURATED                   1189
#define IDC_ADJUSTTIME                  1192
#define IDC_ADJUSTREPEAT                1193
#define IDC_APPNOTE                     1194
#define IDC_MQMAX                       1195
#define IDC_CURRENT                     1196
#define IDC_COLLSELECT                  1197
#define IDC_COLLIMATOR                  1198
#define IDC_DEFMA                       1199
#define IDC_LIST1                       1200
#define IDC_STD                         1200
#define IDC_VARIABLE0                   1201
#define IDC_VARIABLE1                   1202
#define IDC_RADIO3                      1203
#define IDC_STYLED0                     1203
#define IDC_RADIO4                      1204
#define IDC_STYLED1                     1204
#define IDC_RADIO5                      1205
#define IDC_STYLED2                     1205
#define IDC_THICKUNIT0                  1206
#define IDC_THICKUNIT1                  1207
#define IDC_THICKUNIT2                  1208
#define IDC_THICKUNIT3                  1209
#define IDC_THICKUNIT4                  1210
#define IDC_PRECISION                   1211
#define IDC_INDEX                       1212
#define IDC_MODIFYTIME                  1213
#define IDC_MEASURETIME                 1214
#define IDC_CORRECTTIME                 1215
#define IDC_REPEAT                      1216
#define IDC_CONTENTUNIT0                1217
#define IDC_CONTENTUNIT1                1218
#define IDC_CONTENTUNIT2                1219
#define IDC_CONTENTUNIT3                1220
#define IDC_CONTENTUNIT4                1221
#define IDC_ARRAYSIZE                   1222
#define IDC_NAME                        1223
#define IDC_SEC                         1224
#define IDC_STATUS                      1225
#define IDC_EDIT1                       1226
#define IDC_HV30                        1226
#define IDC_LAST_B                      1226
#define IDC_STD_TAG                     1226
#define IDC_LIST                        1227
#define IDC_DEFMALIST                   1227
#define IDC_ELEMRIGHT                   1227
#define IDC_HV40                        1227
#define IDC_LAST_K                      1227
#define IDC_CALCULATED                  1228
#define IDC_HV50                        1228
#define IDC_HI30                        1229
#define IDC_CURR_H2500                  1229
#define CG_IDC_PROGDLG_PROGRESS         1230
#define IDC_HI40                        1230
#define IDC_CURR_PEAK                   1230
#define CG_IDC_PROGDLG_STATUS           1231
#define IDC_HI50                        1231
#define IDC_SCALE                       1231
#define IDC_CURR_H2501                  1231
#define IDC_WZLIST                      1232
#define IDC_ENGB                        1232
#define IDC_CALIB_TIME                  1232
#define IDC_STDLIST                     1233
#define IDC_ENGK                        1233
#define IDC_ELEMLEFT                    1234
#define IDC_ENGC1                       1234
#define IDC_ENGC2                       1235
#define IDC_STDGRID                     1237
#define IDC_RADIO1                      1238
#define IDC_RADIO2                      1239
#define IDC_BUTTON1                     1239
#define IDC_BUTTON2                     1240
#define IDC_BUTTON3                     1241
#define IDC_H2500                       1242
#define IDC_BETHICK                     1243
#define IDC_BUTTON4                     1244
#define IDC_FLTAL                       1245
#define IDC_BUTTON6                     1246
#define IDC_FLTNI                       1247
#define IDC_AUTOCURRENT                 1247
#define IDC_TAKEOFF                     1248
#define IDC_CALIBTIP                    1248
#define IDC_EMGERMENT                   1249
#define IDC_LAST_H2500                  1249
#define IDC_TARGET                      1250
#define IDC_CALIBTITLE                  1250
#define IDC_INCIDENT                    1251
#define IDC_CALIBSTATISTIC_LIST         1251
#define IDC_BUTTON5                     1252
#define IDC_CALIBARRAY_LIST             1252
#define IDC_H2500STEP                   1253
#define IDC_CALIBVIDEO                  1253
#define IDC_CALIBLASTRESULT             1254
#define IDC_CALIB_START                 1255
#define IDC_CALIB_STOP                  1256
#define IDC_ELE01                       2001
#define IDC_ELE02                       2002
#define IDC_ELE03                       2003
#define IDC_ELE04                       2004
#define IDC_ELE05                       2005
#define IDC_ELE06                       2006
#define IDC_ELE07                       2007
#define IDC_ELE08                       2008
#define IDC_ELE09                       2009
#define IDC_ELE10                       2010
#define IDC_ELE11                       2011
#define IDC_ELE12                       2012
#define IDC_ELE13                       2013
#define IDC_ELE14                       2014
#define IDC_ELE15                       2015
#define IDC_ELE16                       2016
#define IDC_ELE17                       2017
#define IDC_ELE18                       2018
#define IDC_ELE19                       2019
#define IDC_ELE20                       2020
#define IDC_ELE21                       2021
#define IDC_ELE22                       2022
#define IDC_ELE23                       2023
#define IDC_ELE24                       2024
#define IDC_ELE25                       2025
#define IDC_ELE26                       2026
#define IDC_ELE27                       2027
#define IDC_ELE28                       2028
#define IDC_ELE29                       2029
#define IDC_ELE30                       2030
#define IDC_ELE31                       2031
#define IDC_ELE32                       2032
#define IDC_ELE33                       2033
#define IDC_ELE34                       2034
#define IDC_ELE35                       2035
#define IDC_ELE36                       2036
#define IDC_ELE37                       2037
#define IDC_ELE38                       2038
#define IDC_ELE39                       2039
#define IDC_ELE40                       2040
#define IDC_ELE41                       2041
#define IDC_ELE42                       2042
#define IDC_ELE43                       2043
#define IDC_ELE44                       2044
#define IDC_ELE45                       2045
#define IDC_ELE46                       2046
#define IDC_ELE47                       2047
#define IDC_ELE48                       2048
#define IDC_ELE49                       2049
#define IDC_ELE50                       2050
#define IDC_ELE51                       2051
#define IDC_ELE52                       2052
#define IDC_ELE53                       2053
#define IDC_ELE54                       2054
#define IDC_ELE55                       2055
#define IDC_ELE56                       2056
#define IDC_ELE57                       2057
#define IDC_ELE58                       2058
#define IDC_ELE59                       2059
#define IDC_ELE60                       2060
#define IDC_ELE61                       2061
#define IDC_ELE62                       2062
#define IDC_ELE63                       2063
#define IDC_ELE64                       2064
#define IDC_ELE65                       2065
#define IDC_ELE66                       2066
#define IDC_ELE67                       2067
#define IDC_ELE68                       2068
#define IDC_ELE69                       2069
#define IDC_ELE70                       2070
#define IDC_ELE71                       2071
#define IDC_ELE72                       2072
#define IDC_ELE73                       2073
#define IDC_ELE74                       2074
#define IDC_ELE75                       2075
#define IDC_ELE76                       2076
#define IDC_ELE77                       2077
#define IDC_ELE78                       2078
#define IDC_ELE79                       2079
#define IDC_ELE80                       2080
#define IDC_ELE81                       2081
#define IDC_ELE82                       2082
#define IDC_ELE83                       2083
#define IDC_ELE84                       2084
#define IDC_ELE85                       2085
#define IDC_ELE86                       2086
#define IDC_ELE87                       2087
#define IDC_ELE88                       2088
#define IDC_ELE89                       2089
#define IDC_ELE90                       2090
#define IDC_ELE91                       2091
#define IDC_ELE92                       2092
#define IDC_LANTHANIDE                  2093
#define ID_MENU_OPENVIDEO               32771
#define ID_MENU_CLOSEVIDEO              32772
#define ID_MENU_SWITCHWZ                32773
#define ID_MENU_NEWWZ                   32774
#define ID_MENU_OPENWZ                  32775
#define ID_MENU_DELWZ                   32776
#define ID_MENU_NEWDEFMA                32777
#define ID_MENU_OPENDEFMA               32778
#define ID_MENU_DELDEFMA                32779
#define ID_MENU_CPDEFMA                 32780
#define ID_MENU_NORMALIZE               32781
#define ID_MENU_CORRECT                 32782
#define ID_MENUITEM32783                32783
#define ID_MENU_AUTOSORT                32783
#define ID_MENU_OPENSPECVIEW            32784
#define ID_MENU_OPENSPEC                32785
#define ID_MENU_SAVESPEC                32786
#define ID_MENU_AUTOSAVE                32787
#define ID_MENU_DAEMON                  32788
#define ID_MENU_OPENTUBE                32789
#define ID_MENU_CLOSETUBE               32790
#define ID_MENU_STDBY                   32791
#define ID_MENU_CALCAVG                 32792
#define ID_MENU_CALCSIGL                32793
#define ID_MENU_DELRST                  32794
#define ID_MENU_DELRSTALL               32795
#define ID_MENU_EXITSPEC                32796
#define ID_MENU_AUTOSCALE               32797
#define ID_MENU_USERSCALE               32798
#define ID_MENU_XEXTEND                 32799
#define ID_MENU_XCONTRACT               32800
#define ID_MENU_YEXTEND                 32801
#define ID_MENU_YCONTRACT               32802
#define ID_MENU_FILL                    32803
#define ID_MENU_SETLINE                 32804
#define ID_MENU_STB                     32806
#define ID_STARTSTB                     32807
#define ID_STOPSTB                      32808
#define ID_QUERYSTB                     32810
#define ID_CLOSESTB                     32811
#define ID_MENU_ELEMENT                 32819
#define ID_MENU_WZELEMENT               32820
#define ID_MENU_PERIODICTABLE           32821
#define ID_MENU_MEASUREPARAM            32822
#define ID_MENU_CREATEWZ                32823
#define ID_MENU_PUREELEMENT             32824
#define ID_MENU_MATERIAL                32825
#define ID_MENU_ZOOMVIDEO               32826
#define ID_MENU_SAVEVIDEO               32827
#define ID_MENU_THICK                   32828
#define ID_MENU_TESTDEFMA               32829
#define ID_MENU_CLOSESPEC               32830
#define ID_MENU_CLOSEALLSPEC            32831
#define ID_MENU_FPCALIB                 32834
#define ID_MENU_TESTPF                  32835
#define ID_MENU_FPCALC                  32836
#define ID_MENU_CORRECTBASE             32837
#define ID_MENU_CORRECTSTD              32838
#define ID_MENU_QUITCALIB               32839
#define ID_MENU_PARAM                   32841
#define ID_MENU_XYZ                     32842
#define ID_MENU_CROSS                   32843
#define ID_MENU_ENERGY_CALIB            32844
#define ID_MENU_CALIB_REDO              32845
#define ID_MENU_CALIB_SKIP              32846
#define ID_MENU_CALIB_LOAD              32847
#define IDS_SYSPARAMHASBEENSENT         61447
#define IDS_INFO_OCUUPIED_INFO          61448
#define IDS_INFO_OCUUPY_STBTEST         61449
#define IDS_INFO_OCUUPY_MEASURE         61450
#define IDS_INFO_OCUUPY_SPECTRUM        61451
#define IDS_INFO_OCUUPY_STBWARN         61452

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        196
#define _APS_NEXT_COMMAND_VALUE         32857
#define _APS_NEXT_CONTROL_VALUE         1257
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
