#if !defined(AFX__HPAGEBREAKS_H__3216D019_A321_4068_8266_8996F5F958F6__INCLUDED_)
#define AFX__HPAGEBREAKS_H__3216D019_A321_4068_8266_8996F5F958F6__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class C_PageBreak;

/////////////////////////////////////////////////////////////////////////////
// C_HPageBreaks wrapper class

class C_HPageBreaks : public COleDispatchDriver
{
public:
	C_HPageBreaks() {}		// Calls COleDispatchDriver default constructor
	C_HPageBreaks(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	C_HPageBreaks(const C_HPageBreaks& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void Add(long Row);
	void Remove(long Index);
	void Clear();
	long Count();
	C_PageBreak Item(long Index);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__HPAGEBREAKS_H__3216D019_A321_4068_8266_8996F5F958F6__INCLUDED_)
