#if !defined(AFX__IMAGE_H__8006C3AA_D954_4059_9C0B_B10DC7DE141E__INCLUDED_)
#define AFX__IMAGE_H__8006C3AA_D954_4059_9C0B_B10DC7DE141E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// C_Image wrapper class

class C_Image : public COleDispatchDriver
{
public:
	C_Image() {}		// Calls COleDispatchDriver default constructor
	C_Image(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	C_Image(const C_Image& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetKey();
	void SetKey(LPCTSTR lpszNewValue);
	CPicture GetPicture();
	void SaveAs(LPCTSTR Filename);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__IMAGE_H__8006C3AA_D954_4059_9C0B_B10DC7DE141E__INCLUDED_)
